// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOaoPNkNJnTie9th4sJU69fvKk7zIz3jo',
    appId: '1:22330851213:web:5d3ffa5911c0b918df87c4',
    messagingSenderId: '22330851213',
    projectId: 'flameup-4df68',
    authDomain: 'flameup-4df68.firebaseapp.com',
    storageBucket: 'flameup-4df68.firebasestorage.app',
    measurementId: 'G-CP49CXEQ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfjfo1vl2ZNO6u5RugNSDA3kAj_C9vro4',
    appId: '1:22330851213:android:aca9dc63e0a7fe62df87c4',
    messagingSenderId: '22330851213',
    projectId: 'flameup-4df68',
    storageBucket: 'flameup-4df68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3SWUPP3XYxiQYV7SBk_Q0hdweql-wA5A',
    appId: '1:22330851213:ios:85f9d7c5261e73fcdf87c4',
    messagingSenderId: '22330851213',
    projectId: 'flameup-4df68',
    storageBucket: 'flameup-4df68.firebasestorage.app',
    iosBundleId: 'flameup.com.flameup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3SWUPP3XYxiQYV7SBk_Q0hdweql-wA5A',
    appId: '1:22330851213:ios:85f9d7c5261e73fcdf87c4',
    messagingSenderId: '22330851213',
    projectId: 'flameup-4df68',
    storageBucket: 'flameup-4df68.firebasestorage.app',
    iosBundleId: 'flameup.com.flameup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOaoPNkNJnTie9th4sJU69fvKk7zIz3jo',
    appId: '1:22330851213:web:f776dea1301f95a3df87c4',
    messagingSenderId: '22330851213',
    projectId: 'flameup-4df68',
    authDomain: 'flameup-4df68.firebaseapp.com',
    storageBucket: 'flameup-4df68.firebasestorage.app',
    measurementId: 'G-MEG7M575XS',
  );

}